# configure redis.
- name: configure redis
  template:
    src: redis.conf.j2
    dest: "{{redis.config_dir}}/redis.conf"
    owner: root
    group: root
    mode: 0600
  tags:
    - configure

# create empty pid file.
- name: create empty pid file
  file:
    path: "{{redis.system_dir}}/process.pid"
    state: touch
    owner: root
    group: root
    mode: 0600
  tags:
    - configure

# configure supervisor for redis.
- name: configure supervisor for redis
  template:
    src: supervisor.ini.j2
    dest: /etc/supervisord.d/redis.ini
    owner: root
    group: root
    mode: 0600
  notify:
    - restart redis
  tags:
    - configure
